BADGES_TARGET = niv1__pgcd2 niv1__age niv1__hello niv1__affine niv1__fact niv3__fibo niv3__fact_papl niv2__val_binaire

COMMON := ../common
include $(COMMON)/rules.mk

pgcd2: pgcd2.o fct_pgcd2.o

fact: fact.o fct_fact.o fct_mult.o

fact_papl: fact_papl.o fct_fact_papl.o

age: age.o fct_age.o

hello: hello.o fct_hello.o

affine: affine.o fct_affine.o fct_mult.o

fibo: fibo.o fct_fibo.o

val_binaire: val_binaire.o fct_val_binaire.o
